apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mayank
  name: mayank
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mayank
  type: NodePort
